### ISSUE TITLE
 [uvm macros, indentation] Indenting uvm macros with begin/end semantic

### ISSUE THREAD

**Issue by msfschaffner** [google/verible#27]
should:
```systemverilog
`uvm_object_utils_begin(ibex_mem_intf_seq_item)
  `uvm_field_int(addr, UVM_DEFAULT)
  `uvm_field_enum(rw_e, read_write, UVM_DEFAULT)
  `uvm_field_int(be, UVM_DEFAULT)
  `uvm_field_int(data, UVM_DEFAULT)
  `uvm_field_int(gnt_delay, UVM_DEFAULT)
  `uvm_field_int(rvalid_delay, UVM_DEFAULT)
  `uvm_field_int(error, UVM_DEFAULT)
`uvm_object_utils_end `uvm_object_new
```

is:
```systemverilog
`uvm_object_utils_begin(ibex_mem_intf_seq_item)
`uvm_field_int(addr, UVM_DEFAULT)
`uvm_field_enum(rw_e, read_write, UVM_DEFAULT)
`uvm_field_int(be, UVM_DEFAULT)
`uvm_field_int(data, UVM_DEFAULT)
`uvm_field_int(gnt_delay, UVM_DEFAULT)
`uvm_field_int(rvalid_delay, UVM_DEFAULT)
`uvm_field_int(error, UVM_DEFAULT)
`uvm_object_utils_end `uvm_object_new
```

**Comment by msfschaffner** [comment]
b/145155336

**Comment by ldalek-antmicro** [comment]
Hey @fangism,
I've fixed this issue by detecting `uvm_object_utils_begin` and `uvm_object_utils_end` leaves and by
indenting each 'kMacroCall' but I'm not sure if this approach is correct. I was thinking about changing
CST tree and indenting it like it's done between 'begin' and 'end' keywords.
Can you give me some hints how this should be done?

**Comment by fangism** [comment]
There is certainly more than one way this could be accomplished.  And here is but one idea:

Allow macro calls to be processed and indented as-is, but in the fix-up phase after a visiting a node of type `kMacroCall` that matches `uvm.*end`, iterate backwards over the siblings until reaching `uvm.*begin` and adjust the indentation of partitions in between them.

mock up:
```
// assuming we've identified a begin/end pair that marks the range of interest...
for (auto& partition : /* range between begin/end pair */ ) {
 partition.ApplyPreOrder([&](UnwrappedLine& line) {
    line.SetIndentationSpaces(line.IndentationSpaces() + style_.indentation_spaces);
  });
}
```

references:
https://github.com/google/verible/blob/b1628f95aa58406a1ffa3f1d91354eae98d50930/common/util/vector_tree.h#L491
https://github.com/google/verible/blob/b1628f95aa58406a1ffa3f1d91354eae98d50930/common/formatting/unwrapped_line.h#L82

This *feels* simpler to me because 
1) we don't need to track any state during forward analysis (from `uvm.*begin`) (I'm not opposed to state-tracking.)
2) iterating through token partition siblings guarantees we find corresponding begin/end pairs (unless user's code is mismatched, in which case, we could just take no fix-up action)
3) it doesn't alter the shape of any existing partitions, only indentation amounts

The test cases for this should be rather interesting, there are many paired UVM macros like this.  We'll want to cover potentially weird cases like:

```
  `uvm_blah1_begin(...)
    ...  // indented more
  `uvm_blah1_end
  ...  // normal indentation
  `uvm_blah2_begin(...)
    ...  // indented more
  `uvm_blah2_end
  ...  // normal indentation
```

**Comment by ldalek-antmicro** [comment]
Okay. First of all thanks for comment. It was very useful.
I've prepared PR #113 with changes.

I've decided to put every `uvm` macro in its own unwrapped line:
https://github.com/google/verible/pull/113/files#diff-7872d97b05fbc6f2a64cf14b8ae74d75R665
https://github.com/google/verible/pull/113/files#diff-7872d97b05fbc6f2a64cf14b8ae74d75R910

And then indent macros between `begin` and `end` keywords like you suggested:
https://github.com/google/verible/pull/113/files#diff-7872d97b05fbc6f2a64cf14b8ae74d75R924
